### ISSUE TITLE
metadata setting to FULL_TABLE doesn't do a full_sync it seems to always use incremental

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-universal-file#126]
Maybe I've done something wrong

```yml
  - name: tap-universal-file
    namespace: tap_universal_file
    pip_url: tap-universal-file[s3]@git+https://github.com/MeltanoLabs/tap-universal-file.git
    capabilities:
    - state
    - catalog
    - discover
    - about
    - stream-maps
    settings:
    - name: stream_name
    - name: protocol
    - name: file_path
    - name: file_regex
    - name: file_type
    - name: fail_when_no_files_found
      kind: boolean
    - name: compression
    - name: additional_info
      kind: boolean
    - name: start_date
      kind: date_iso8601
    - name: delimited_error_handling
    - name: delimited_delimiter
    - name: delimited_quote_character
    - name: delimited_header_skip
      kind: integer
    - name: delimited_footer_skip
      kind: integer
    - name: delimited_override_headers
      kind: array
    - name: jsonl_error_handling
    - name: jsonl_sampling_strategy
    - name: jsonl_type_coercion_strategy
    - name: avro_type_coercion_strategy
    - name: parquet_type_coercion_strategy
    - name: s3_anonymous_connection
    - name: AWS_ACCESS_KEY_ID
      kind: string
      sensitive: true
    - name: AWS_SECRET_ACCESS_KEY
      kind: string
      sensitive: true
    - name: caching_strategy
    metadata:
      '*':
        replication-method: FULL_TABLE
```

With this set I keep getting incremental syncs.
